import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./styles/globals.scss";
import Navbar from "../components/Navbar/Navbar";
import Footer from "../components/Footer/Footer";
import { getServerSession } from "next-auth";
import SessionProvider from "../lib/SessionProvider";
import ReduxProvider from ".././redux/Provider";

const inter = Inter({
  subsets: ["latin"],
  weight: ["400", "500", "600", "700"],
});

export const metadata: Metadata = {
  title: "Eccomerce shop",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const session = await getServerSession();

  return (
    <html lang="en">
      <body className={inter.className}>
        <SessionProvider session={session}>
          <div className="wrapper">
            <ReduxProvider>
              <Navbar />
              <div className="content">{children}</div>
              <Footer />
            </ReduxProvider>
          </div>
        </SessionProvider>
      </body>
    </html>
  );
}
